export const types = {
  addDigit: 'addDigit',
  addFirstNum: 'addFirstNum',
  addSecondNum: 'addSecondNum',
  resetOps: 'C',
  post2neg: '+/-',
  percent: '%',
  delete: 'del',
  floatingPt: '.',
  sum: '+',
  sub: '-',
  mult: 'X',
  div: '/',
  total: '=',
};
